export const LOAD_TASKS = 'LOAD_TASKS'
export const LOADING_TASKS = 'LOADING_TASKS'
export const TASKS_LOADED = 'TASKS_LOADED'
export const DELETE_TASK = 'DELETE_TASK'
export const CREATE_TASK = 'CREATE_TASK'
export const COMPLETE_TASK = 'COMPLETE_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
export const RESET_OPERATIONS = 'RESET_OPERATIONS'
export const SET_CONTEXT = 'SET_CONTEXT'
export const SELECT_TASK_TYPE = 'SELECT_TASK_TYPE'
export const LOGGED_OUT = 'LOGGED_OUT'
export const CHECK_AUTH = 'CHECK_AUTH'
export const CHECKING_AUTH = 'CHECKING_AUTH'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGOUT = 'LOGOUT'
export const LOGIN = 'LOGIN'
export const LOGGING_IN = 'LOGGING_IN'
export const ANIMATING_TASK_TYPE = 'ANIMATING_TASK_TYPE'
export const ERROR_AUTH = 'ERROR_AUTH'
export const TASK_SELECTED = 'TASK_SELECTED'



